// Generates src/icons-android.ts from the pinned @material-symbols/svg-400
// package (Apache-2.0, © Google). Run `bun run ./scripts/gen-icons.ts` after
// bumping the package or changing the icon list.
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const source = join(
  root,
  "node_modules/@material-symbols/svg-400/rounded",
);

/** Icons the Android surfaces draw, in the rounded Material Symbols style. */
const ICONS = [
  "add",
  "add_photo_alternate",
  "apps",
  "arrow_back",
  "attach_file",
  "backspace",
  "call",
  "check",
  "check_circle-fill",
  "check_small",
  "close",
  "content_paste",
  "delete",
  "done_all",
  "expand",
  "gif_box",
  "image",
  "keyboard_capslock",
  "keyboard_return",
  "lock",
  "mic-fill",
  "mood",
  "more_vert",
  "notifications_off",
  "photo_camera",
  "photo_library",
  "play_arrow-fill",
  "reply",
  "schedule",
  "search",
  "send-fill",
  "settings",
  "shift",
  "signal_cellular_4_bar-fill",
  "signal_wifi_4_bar-fill",
  "translate",
  "verified",
  "videocam",
] as const;

const entries: [string, string[]][] = [];
const missing: string[] = [];
for (const name of ICONS) {
  const file = join(source, `${name}.svg`);
  const svg = await readFile(file, "utf8").catch(() => null);
  if (!svg) {
    missing.push(name);
    continue;
  }
  const paths = [...svg.matchAll(/\bd="([^"]+)"/g)].map((match) => match[1]!);
  if (!paths.length) {
    missing.push(name);
    continue;
  }
  entries.push([name, paths]);
}
if (missing.length) {
  console.error(`Missing icons: ${missing.join(", ")}`);
  process.exit(1);
}
entries.sort(([a], [b]) => a.localeCompare(b));

const body = entries
  .map(([name, paths]) => `  ${JSON.stringify(name)}: [${paths.map((d) => `\n    ${JSON.stringify(d)},`).join("")}\n  ],`)
  .join("\n");

const output = `// Generated by scripts/gen-icons.ts from @material-symbols/svg-400.
// Material Symbols are © Google, licensed Apache-2.0; see THIRD-PARTY-NOTICES.
// Material Symbols use a "0 -960 960 960" viewBox and fill rendering.
export const androidIconPaths = {
${body}
} as const;
export type AndroidIconName = keyof typeof androidIconPaths;
`;

await writeFile(join(root, "src", "icons-android.ts"), output);
console.log(`Wrote ${entries.length} icons to src/icons-android.ts`);
